REM   Script: Session 01
REM   401k Calc

SELECT FIRST_NAME || ' ' || LAST_NAME AS EMP_NAME, SALARY * 10,  
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) AS Work_Span, 
    ROUND((SALARY + 0.6*SALARY) * ((POWER(1 + (0.06/12), (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE)) * 12)  - 1) / (0.06/12))) 
    AS RETIREMENT_FUNDS 
FROM HR.EMPLOYEES;

